name: pelphix
channels:
  - pytorch
  - "nvidia/label/cuda-11.8.0"
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision

  # Deepdrr deps
  - cuda-toolkit
  - cuda-runtime
  - cuda-nvprof
  - cuda-gdb
  - cuda-profiler-api

  - pip
  - pip:
      - -r requirements.txt
      - -e .

