name: pelphix
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - pycuda=2022.2 # 2021.1
  - cudatoolkit-dev
  - pip
  - pip:
      - -r requirements.txt
      - -e .
