_target_: pelphix.models.swin_unet.SwinTransformerUnet
img_size: ${image_size}
patch_size: 4
in_chans: 3
num_classes: 17 # gets overwritten
embed_dim: 96
depths: [2, 2, 2, 2]
depths_decoder: [1, 2, 2, 2]
num_heads: [3, 6, 12, 24]
window_size: 7
mlp_ratio: 4.0
qkv_bias: true
qk_scale: null
drop_rate: 0.0
attn_drop_rate: 0.0
drop_path_rate: 0.1
ape: false
patch_norm: true
use_checkpoint: false
final_upsample: "expand_first"
